### ISSUE TITLE
space-id vs space key

### ISSUE THREAD

**Issue by AX-LLaidley** [Bhacaz/docs-as-code-confluence#1]
I noticed when I was trying to get this GHA to work, that while the documentation specifies to use the `space-id`, the space key should actually be used. Using the space ID results in a 404 when the action is run, with a message that no space with that key exists. 

Please update the documentation to reflect that the space key is required, rather than the ID.

**Comment by Bhacaz** [comment]
Hi, thanks for the issue. I [updated](https://github.com/Bhacaz/docs-as-code-confluence/commit/6ec19adadb6ab430dbe89fb4ec9442ce5a00cc11) the README to me more clear about want to put for the argument `space-id`.

The best would be to change the argument name. I'll make the change for an other version.
